{application,erlangDC,
             [{description,[]},
              {vsn,"1"},
              {registered,[erlangDC_app,dc_server]},
              {applications,[kernel,stdlib]},
              {mod,{erlangDC_app,[]}},
              {env,[]},
              {modules,[connection,dc_server,erlangDC_app,erlangDC_sup,
                        management_message,rt_message_handler,workcycle]}]}.
